(pushnew (ccl:current-directory) ql:*local-project-directories*)
(declaim (optimize (debug 3)))

(ql:quickload "tree")
(in-package :tree)
(format t "Please specifiy player ID:")
(defparameter *cli-player-id* (read))
(format t "~%")
(defvar test-tree)
(setq test-tree (make-instance 'tree :player-id *cli-player-id*))
